DROP TABLE IF EXISTS A;
CREATE TABLE A (
    a int
);

DROP TABLE IF EXISTS B;
CREATE TABLE B (
    b1 int,
    b2 int
);

DROP TABLE IF EXISTS C;
CREATE TABLE C (
    x  float
);

INSERT INTO A VALUES(1);
INSERT INTO A VALUES(5);
INSERT INTO A VALUES(-1);
INSERT INTO B VALUES(1,3);
INSERT INTO B VALUES(2,9);
INSERT INTO C VALUES(1.5);
INSERT INTO C VALUES(-2.3);
INSERT INTO C VALUES(3.9);

DELIMITER $$
CREATE FUNCTION f(x double)
RETURNS double
DETERMINISTIC
BEGIN
    return x * x;
END
$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE sp_getvalues()
BEGIN
    SELECT max(a) FROM A;
    SELECT max(b1), min(b2) FROM B;
    SELECT sum(x) FROM C;
END
$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE sp_getvaluesbyref(OUT res int)
BEGIN
    SELECT max(a) INTO res FROM A;
END
$$
DELIMITER ;


